### ISSUE TITLE
Current issues

### ISSUE THREAD

**Issue by danielstuart14** [Magisk-Modules-Repo/Xiaomi-Mi-A2-Camera#5]
I'm going to make a list with all the bugs I found so far. This way it's easier to fix them and also the users can be aware before trying it.

### What I found so far that isn't working:

- [ ] Shutter sound can't be muted (Only if you put you phone in silent mode)
- [ ] Burst mode crashes the app (Disabled for now)
- [x] App crashes on Android P

**Comment by joeyhuab** [comment]
Thanks for this. :) Really important we could include this in the XDA thread.

**Comment by joeyhuab** [comment]
The app crashes for me on Android P. Weird.

**Comment by danielstuart14** [comment]
After checking the camera code with jadx, I found out that we need zxing's Barcode Scanner app installed for the built-in qrcode reader to work... I think it comes already installed in MIUI/Stock.

Playstore: https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=pt_BR
zxing's app source code: https://github.com/zxing/zxing

@joeyhuab we actually only need com.google.zxing.client.android.SCAN, maybe we can include it in the module?

**Comment by joeyhuab** [comment]
We can definitely add it in although I'm not really good at coding those
in. You may feel free to do so if you have knowledge with the source codes.

**Comment by danielstuart14** [comment]
I'll do some tests here. 
Maybe we can wait for the Mi A2 stock rom to be released, before trying to fix these bugs, A2 camera should work fine with our device. (It has a 20mp sensor, but it's converted to 12mp by the HAL. So the camera app sees it as 2 12mp sensors.)

**Comment by danielstuart14** [comment]
Yeah! I'll try to write a python script for auto-patching, this will make easier for patching any new miui camera.

Just an update about the QR Code, with zxing's app installed, it now recognizes that there's a QRCode, but doesn't do anything yet. I found out that we still need an app called "com.xiaomi.scanner". I wasn't able to found it in the stock, I'll keep searching. Really odd.

Code in the app that calls for "com.xiaomi.scanner":
```
try {
                ActivityBase activityBase = this.mActivity;
                activityBase.dismissKeyguard();
                Intent intent = new Intent("miui.intent.action.receiverResultBarcodeScanner");
                intent.setPackage("com.xiaomi.scanner");
                intent.putExtra("result", this.mResult);
                activityBase.startActivity(intent);
                activityBase.setJumpFlag(3);
            } catch (ActivityNotFoundException ex) {
                ex.printStackTrace();
                Log.e("QRCodeManager", "check if BarcodeScanner tool is installed or not");
            }
```

**Comment by danielstuart14** [comment]
Well, my bad, it seems that tissot has the qrcode disabled by default. I'll update the apk disabling it on custom roms, as well. (Maybe we can make it work later, hacking this call to xiaomi's scanner)

About the burst mode crash, it seems to be rom related.
I get this error:
```07-22 19:29:15.600   660 22736 I QCamera : <HAL><INFO> take_picture: 919: [KPI Perf]: E PROFILE_TAKE_PICTURE camera id 3
07-22 19:29:15.601   660  4213 E QCamera : <HAL><ERROR> procEvtPreviewPicTakingState: 3505: Error!! cannot handle evt(24) in state(7)
07-22 19:29:15.601   660 22736 E QCamera : <HAL><ERROR> take_picture: 986: pre_take_picture failed with ret = -38```

Custom roms are using the stock camera lib, which is a pain to debug. (for example, evt 24 is QCAMERA_SM_EVT_START_AUTO_FOCUS in the CAF hal, but in xiaomi's HAL it's QCAMERA_SM_EVT_PRE_TAKE_PICTURE)... It seems that mLongshotEnabled is the issue. We would need a patched frameworks_av for it to be fixed. It isn't being enabled when we do burst shots.
The best would be a OSS camera hal, but it's up to the devs.

**Comment by danielstuart14** [comment]
B/W photo and burst shot crash are related to some methods that don't exist.
log:
```
07-24 00:03:52.840  4117  4191 W Camera  : ReflectUtil#callMethod
07-24 00:03:52.840  4117  4191 W Camera  : java.lang.NoSuchMethodException: getFocusState []
07-24 00:03:52.840  4117  4191 W Camera  :      at java.lang.Class.getMethod(Class.java:2068)
07-24 00:03:52.840  4117  4191 W Camera  :      at java.lang.Class.getMethod(Class.java:1690)
07-24 00:03:52.840  4117  4191 W Camera  :      at com.android.camera.aosp_porting.ReflectUtil.callMethod(ReflectUtil.java:37)
07-24 00:03:52.840  4117  4191 W Camera  :      at com.android.camera.hardware.QcomCameraProxy.isFocusSuccessful(QcomCameraProxy.java:121)
07-24 00:03:52.840  4117  4191 W Camera  :      at com.android.camera.CameraManager$CameraHandler.handleMessage(CameraManager.java:279)
07-24 00:03:52.840  4117  4191 W Camera  :      at android.os.Handler.dispatchMessage(Handler.java:106)
07-24 00:03:52.840  4117  4191 W Camera  :      at android.os.Looper.loop(Looper.java:164)
07-24 00:03:52.840  4117  4191 W Camera  :      at android.os.HandlerThread.run(HandlerThread.java:65)
```

Both methods getFocusState & setLongshot don't seem to exist in aosp.

getFocusState seems to be at SystemUI.apk (???) on stock. setLongShot I didn't find yet.

**Comment by joeyhuab** [comment]
I can look for them in stock ROM if you would like.

**Comment by danielstuart14** [comment]
hey @joeyhuab , I think I found it. camera.msm8953.so matches for 'setLongShot'.
Maybe devs need to update their roms with latest blobs?

**Comment by joeyhuab** [comment]
Yes. I feel this is the issue. Thanks for checking.

https://androidfilehost.com/?fid=5862345805528055196

Check the APK here as well and see if it has the device check.

**Comment by danielstuart14** [comment]
@joeyhuab it has some of the patches for disabling device check. (QR code is still enabled)

**Comment by joeyhuab** [comment]
Thanks! Let's get to work with the Mi A2 Camera port?

**Comment by danielstuart14** [comment]
We'd need a rom dump, since xiaomi didn't release stock yet.

**Comment by joeyhuab** [comment]
I can link you to a dump location. https://t.me/mia2official
Please join. :)

**Comment by joeyhuab** [comment]
Have you checked the telegram channel? :) Most files like priv-app have
been dumped there already.

**Comment by danielstuart14** [comment]
Yeah, I wasn't able to get it to work.
I'll keep an eye on it, tho.

For now, I found a way to enable 1/8 sec exposure. (Anything more than this doesn't seem to have any difference... probably the hal just timeouts)
I'll make a PR soon.

**Comment by joeyhuab** [comment]
Alright. Currently awaiting it! Thanks so much!

**Comment by joeyhuab** [comment]
Hey buddy! I got the Camera apk folder. I hope you can deodex it. :) Will
really help. Thank you so much

https://github.com/TadiT7/xiaomi_jasmine_dump/tree/jasmine-user-8.1.0-OPM1.171019.011-V9.6.5.0.ODIMIFE-release-keys/system/system/priv-app/MiuiCamera

**Comment by joeyhuab** [comment]
Hi man. You still there? Been waiting from a response from you. We need to
bypass the device check.

**Comment by danielstuart14** [comment]
hey, what's up? 
I was on vacations, I'm back now. 
Send me an email later, I can try to bypass the device check.

**Comment by joeyhuab** [comment]
You got a telegram? Here's the latest version btw. https://drive.google.com/open?id=1jQmJoBgM5871yiBaL-_KonNrsVsmT0m2

**Comment by joeyhuab** [comment]
Checked it already? :)
